LAYER_CONFIG = {
    # Tiny random GPT-2 — minimal RAM + safetensors (loads on older torch; CI / constrained Windows).
    "hf-internal-testing/tiny-random-gpt2": {
        "layers": [1, 3],
        "hidden_dim": 32,
        "has_sae": False,
    },
    "distilgpt2": {
        "layers": [2, 4],
        "hidden_dim": 768,
        "has_sae": False,
    },
    # CPU-friendly open proxies (no HF gate). Pair with 7B+ rows below on GPU machines.
    "TinyLlama/TinyLlama-1.1B-Chat-v1.0": {
        "layers": [4, 11, 18],
        "hidden_dim": 2048,
        "has_sae": False,
        "family": "llama",
    },
    "Qwen/Qwen2.5-0.5B-Instruct": {
        "layers": [6, 12, 18],
        "hidden_dim": 896,
        "has_sae": False,
        "family": "qwen",
    },
    "HuggingFaceTB/SmolLM2-1.7B-Instruct": {
        "layers": [6, 12, 18],
        "hidden_dim": 2048,
        "has_sae": False,
        "family": "mistral",
    },
    # Gated on HF — use after: huggingface-cli login
    "meta-llama/Llama-3.2-1B-Instruct": {
        "layers": [4, 8, 12],
        "hidden_dim": 2048,
        "has_sae": False,
        "family": "llama",
        "gated": True,
    },
    "google/gemma-2-2b-it": {
        "layers": [6, 13, 20],
        "hidden_dim": 2304,
        "has_sae": False,
        "family": "gemma",
        "gated": True,
    },
    "meta-llama/Meta-Llama-3-8B": {
        "layers": [8, 16, 24, 28],
        "hidden_dim": 4096,
        "has_sae": True,
        "sae_release": "llama_scope_lxr_8x",
        "family": "llama",
        "requires_gpu": True,
    },
    "meta-llama/Meta-Llama-3-8B-Instruct": {
        "layers": [8, 16, 24, 28],
        "hidden_dim": 4096,
        "has_sae": True,
        "sae_release": "llama_scope_lxr_8x",
        "family": "llama",
        "requires_gpu": True,
    },
    "mistralai/Mistral-7B-v0.1": {
        "layers": [8, 16, 24],
        "hidden_dim": 4096,
        "has_sae": False,
        "family": "mistral",
        "requires_gpu": True,
    },
    "mistralai/Mistral-7B-Instruct-v0.2": {
        "layers": [8, 16, 24],
        "hidden_dim": 4096,
        "has_sae": False,
        "family": "mistral",
        "requires_gpu": True,
    },
    "Qwen/Qwen2-7B": {
        "layers": [7, 14, 22],
        "hidden_dim": 3584,
        "has_sae": False,
        "family": "qwen",
        "requires_gpu": True,
    },
    "Qwen/Qwen2-7B-Instruct": {
        "layers": [7, 14, 22],
        "hidden_dim": 3584,
        "has_sae": False,
        "family": "qwen",
        "requires_gpu": True,
    },
    "google/gemma-2-9b": {
        "layers": [9, 18, 28],
        "hidden_dim": 3584,
        "has_sae": True,
        "sae_release": "gemma-scope-9b-pt-res",
        "family": "gemma",
        "requires_gpu": True,
    },
    "google/gemma-2-9b-it": {
        "layers": [9, 18, 28],
        "hidden_dim": 3584,
        "has_sae": True,
        "sae_release": "gemma-scope-9b-pt-res",
        "family": "gemma",
        "requires_gpu": True,
    },
}
